version: "3.3"

services:

  app:
    image: youtube-alexa-app
    build: .
    command: ["npm", "run", "dev"]
    volumes:
      - ./package.json:/app/package.json
      # - ./package-lock.json:/app/package-lock.json
      - ./logo.png:/app/logo.png
      - ./api:/app/api
      - ./public:/app/public
      - ./views:/app/views
      - ./index.js:/app/index.js
    ports:
      - "5080:5000"
      - "9229:9229"
    environment:
      DEBUG: "1"
      PORT: "5000"
